# Generated by Django 2.1.7 on 2019-03-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('title', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=120)),
                ('solution', models.CharField(max_length=500)),
                ('difficulty', models.IntegerField()),
                ('year', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
            ],
        ),
    ]
