# Generated by Django 2.1.7 on 2019-04-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trophies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trophies.Trophy')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user_trophy',
            unique_together={('userID', 'trophy')},
        ),
    ]
