# Generated by Django 2.1.7 on 2019-03-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('keyCode', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('expDate', models.DateField()),
            ],
        ),
    ]
