# Generated by Django 2.1.7 on 2019-04-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('ID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('userPass', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
