# Generated by Django 2.1.7 on 2019-03-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trophies', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic_trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophies.Trophy')),
            ],
        ),
    ]
